require('./components/queriers/babia-querygithub')
require('./components/queriers/babia-queryjson')
require('./components/queriers/babia-queryes')
require('./components/others/babia-ui')
require('./components/filters/babia-filter')
require('./components/filters/babia-treebuilder')
require('./components/filters/babia-selector')
require('./components/others/babiaxr-interaction-mapper')
require('./components/others/babiaxr-debug-data')
require('./components/visualizers/babia-pie')
require('./components/visualizers/babia-bars')
require('./components/visualizers/babia-barsmap')
require('./components/visualizers/babia-bubbles')
require('./components/visualizers/babiaxr-codecity')
require('./components/visualizers/babia-city')
require('./components/visualizers/babia-cyls')
require('./components/visualizers/babia-cylsmap')
require('./components/visualizers/babia-doughnut')
require('./components/others/babiaxr-totem')
require('./components/visualizers/babia-terrain')
require('./components/others/babiaxr-navigation_bar')
require('./components/others/babiaxr-event_controller')
require('./components/visualizers/babia-boats')
require('./components/others/babia-lookat')
require('./components/visualizers/babia-network')
require('./components/others/babia-label')
require('./components/others/babia-axis')
require('./components/others/common')
require('./components/geometries/babia-bar')
require('./components/others/babia-controls')
require('./components/others/babia-navigator')
require('./components/others/babia-slider')
require('./components/others/babia-ui-link')
require('./components/others/babia-camera')
require('./common/noti-buffer')
require('./components/geometries/babia-cyl')
require('./components/others/babia-range-selector')

// Assets
pauseButton = require('./components/others/models/pause_button.gltf')
playButton = require('./components/others/models/play_button.gltf')
skipButton = require('./components/others/models/skip_button.gltf')
rewindButton = require('./components/others/models/rewind_button.gltf')
tooltip = require('./components/others/assets/tooltip.png')